//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cleaner {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cleaner.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 你没有输入任何参数，传入-h参数来获取帮助 的本地化字符串。
        /// </summary>
        internal static string argsifempty {
            get {
                return ResourceManager.GetString("argsifempty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NekokeCore @2022 的本地化字符串。
        /// </summary>
        internal static string auther {
            get {
                return ResourceManager.GetString("auther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   _____                   _       _                _____        __ _                          
        /// / ____|                 | |     (_)              / ____|      / _| |                         
        ///| |     ___  _ __ ___  __| |_   _ _ _ __   ___   | (___   ___ | |_| |___      ____ _ _ __ ___ 
        ///| |    / _ \| &apos;__/ _ \/ _` | | | | | &apos;_ \ / _ \   \___ \ / _ \|  _| __\ \ /\ / / _` | &apos;__/ _ \
        ///| |___| (_) | | |  __/ (_| | |_| | | | | | (_) |  ____) | (_) | | | |_ \ V  V / (_| | | |  __/
        /// \_____\___/|_|  \___|\__,_|\__, [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string banner {
            get {
                return ResourceManager.GetString("banner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等待完善 的本地化字符串。
        /// </summary>
        internal static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Simple Cleaner Version 1.0.0 的本地化字符串。
        /// </summary>
        internal static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
    }
}
